on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 
        
      - name: Install Dependencies
        run: npm install
        
      - name: Run index.js
        run: node index.js

name: hello
on: [push]
jobs:
build:

run-on: ubuntu-latest

steps:
-uses : action/checkou@v1
-name: run a one-line script
    run: echo Hello World!
-name: Run a multi-line script
    run: |
    echo Add other actions to build,
    echo test, and deoply your project
