name: NODE.js CI
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 
        
      - name: Install Dependencies
        run: npm install
        
      - name: Run index.js
        run: node index.js

     
